[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npx http-server -p 5000"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[[services]]
  name = "web"
  serviceType = "web"
  sourceDir = "/"