[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/health.html"
  healthcheckTimeout = 60000
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5
  sleepForSeconds = 10

[[services]]
  name = "web"
  serviceType = "web"
  sourceDir = "/"